<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Part;

use Illuminate\Support\Str;


class PartSeeder extends Seeder
{
    public function run()
    {
        $parts = [
            [
                'part_name' => 'Hydraulic Pump',
                'part_slug' => Str::slug('Hydraulic Pump'),
                'part_description' => 'A high-quality hydraulic pump suitable for excavators.',
                'part_price' => 37500000, 
                'part_image_url' => 'https://t4.ftcdn.net/jpg/00/38/21/01/360_F_38210141_dfsw5WM5StsCvWBuMJ0SZexrLsX4aiu4.jpg',
                'part_category' => 'Hydraulic System',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Jakarta Warehouse',
            ],
            [
                'part_name' => 'Excavator Bucket',
                'part_slug' => Str::slug('Excavator Bucket'),
                'part_description' => 'Durable excavator bucket designed for heavy-duty digging.',
                'part_price' => 22500000, 
                'part_image_url' => 'https://s7d2.scene7.com/is/image/Caterpillar/CM20181026-42998-18793?$cc-g$',
                'part_category' => 'Attachment',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Bandung Warehouse',
            ],
            [
                'part_name' => 'Engine Oil Filter',
                'part_slug' => Str::slug('Engine Oil Filter'),
                'part_description' => 'High-performance oil filter for heavy machinery engines.',
                'part_price' => 750000,
                'part_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtPZhaouoO01n_XVpet2LOixJsw_brfVYkCg&s',
                'part_category' => 'Engine Component',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Surabaya Warehouse',
            ],
            [
                'part_name' => 'Track Tensioner',
                'part_slug' => Str::slug('Track Tensioner'),
                'part_description' => 'Reliable track tensioner for bulldozers and excavators.',
                'part_price' => 10500000,
                'part_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC-AHkM4Zxx0ufy-jbxRqh9Obo51W0hfE-6A&s',
                'part_category' => 'Undercarriage',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Medan Warehouse',
            ],
            [
                'part_name' => 'Cabin Air Filter',
                'part_slug' => Str::slug('Cabin Air Filter'),
                'part_description' => 'Effective air filter for operator cabins.',
                'part_price' => 450000, 
                'part_image_url' => 'https://images.tokopedia.net/img/cache/700/VqbcmM/2022/8/3/9e5d87f3-8463-443c-9b5d-c0f070f80acd.jpg',
                'part_category' => 'Cabin Accessories',
                'part_contact' => 'parts@constructionparts.com',
                'part_location' => 'Yogyakarta Warehouse',
            ],
            [
                'part_name' => 'Fuel Injector',
                'part_slug' => Str::slug('Fuel Injector'),
                'part_description' => 'High-precision fuel injector for heavy machinery engines.',
                'part_price' => 5200000,
                'part_category' => 'Engine Component',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Jakarta Warehouse',
            ],
            [
                'part_name' => 'Hydraulic Cylinder',
                'part_slug' => Str::slug('Hydraulic Cylinder'),
                'part_description' => 'Heavy-duty hydraulic cylinder for excavators and loaders.',
                'part_price' => 27500000,
                'part_category' => 'Hydraulic System',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Bandung Warehouse',
            ],
            [
                'part_name' => 'Wheel Loader Tire',
                'part_slug' => Str::slug('Wheel Loader Tire'),
                'part_description' => 'Robust industrial-grade tire for wheel loaders.',
                'part_price' => 12500000,
                'part_category' => 'Undercarriage',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Surabaya Warehouse',
            ],
            [
                'part_name' => 'Radiator Assembly',
                'part_slug' => Str::slug('Radiator Assembly'),
                'part_description' => 'High-performance cooling radiator for construction machinery.',
                'part_price' => 8750000,
                'part_category' => 'Cooling System',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Medan Warehouse',
            ],
            [
                'part_name' => 'Starter Motor',
                'part_slug' => Str::slug('Starter Motor'),
                'part_description' => 'Reliable electric starter motor for heavy equipment.',
                'part_price' => 3600000,
                'part_category' => 'Electrical System',
                'part_contact' => 'parts@constructionparts.com',
                'part_location' => 'Jakarta Warehouse',
            ],
            [
                'part_name' => 'Hydraulic Hose',
                'part_slug' => Str::slug('Hydraulic Hose'),
                'part_description' => 'High-pressure hydraulic hose for construction machinery.',
                'part_price' => 1250000,
                'part_category' => 'Hydraulic System',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Yogyakarta Warehouse',
            ],
            [
                'part_name' => 'Air Compressor',
                'part_slug' => Str::slug('Air Compressor'),
                'part_description' => 'Industrial-grade portable air compressor for construction sites.',
                'part_price' => 15000000,
                'part_category' => 'Pneumatic Equipment',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Bandung Warehouse',
            ],
            [
                'part_name' => 'Brake Pad Set',
                'part_slug' => Str::slug('Brake Pad Set'),
                'part_description' => 'High-friction brake pads for heavy machinery.',
                'part_price' => 2500000,
                'part_category' => 'Brake System',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Surabaya Warehouse',
            ],
            [
                'part_name' => 'Alternator',
                'part_slug' => Str::slug('Alternator'),
                'part_description' => 'Heavy-duty electrical alternator for construction equipment.',
                'part_price' => 4800000,
                'part_category' => 'Electrical System',
                'part_contact' => 'parts@constructionparts.com',
                'part_location' => 'Medan Warehouse',
            ],
            [
                'part_name' => 'Transmission Filter',
                'part_slug' => Str::slug('Transmission Filter'),
                'part_description' => 'High-quality transmission filter for heavy machinery.',
                'part_price' => 1100000,
                'part_category' => 'Transmission System',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Jakarta Warehouse',
            ],
            [
                'part_name' => 'Bulldozer Blade',
                'part_slug' => Str::slug('Bulldozer Blade'),
                'part_description' => 'Durable cutting edge blade for bulldozers.',
                'part_price' => 18500000,
                'part_category' => 'Attachment',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Yogyakarta Warehouse',
            ],
            [
                'part_name' => 'Battery',
                'part_slug' => Str::slug('Battery'),
                'part_description' => 'Heavy-duty industrial battery for construction equipment.',
                'part_price' => 2750000,
                'part_category' => 'Electrical System',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Bandung Warehouse',
            ],
            [
                'part_name' => 'Exhaust Manifold',
                'part_slug' => Str::slug('Exhaust Manifold'),
                'part_description' => 'High-performance exhaust manifold for diesel engines.',
                'part_price' => 6500000,
                'part_category' => 'Engine Component',
                'part_contact' => 'parts@constructionparts.com',
                'part_location' => 'Surabaya Warehouse',
            ],
            [
                'part_name' => 'Hydraulic Valve',
                'part_slug' => Str::slug('Hydraulic Valve'),
                'part_description' => 'Precision control hydraulic valve for excavators.',
                'part_price' => 5750000,
                'part_category' => 'Hydraulic System',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Medan Warehouse',
            ],
            [
                'part_name' => 'Suspension Bushing',
                'part_slug' => Str::slug('Suspension Bushing'),
                'part_description' => 'Durable suspension bushing for heavy machinery.',
                'part_price' => 750000,
                'part_category' => 'Suspension System',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Jakarta Warehouse',
            ],
            [
                'part_name' => 'Turbocharger',
                'part_slug' => Str::slug('Turbocharger'),
                'part_description' => 'High-efficiency turbocharger for diesel engines.',
                'part_price' => 12750000,
                'part_category' => 'Engine Component',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Yogyakarta Warehouse',
            ],
            [
                'part_name' => 'Concrete Vibrator',
                'part_slug' => Str::slug('Concrete Vibrator'),
                'part_description' => 'Electric concrete vibrator for efficient mixing.',
                'part_price' => 4500000,
                'part_category' => 'Concrete Equipment',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Yogyakarta Warehouse',
            ],
            [
                'part_name' => 'Welding Helmet',
                'part_slug' => Str::slug('Welding Helmet'),
                'part_description' => 'Advanced auto-darkening welding helmet with safety features.',
                'part_price' => 1800000,
                'part_category' => 'Safety Equipment',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Bandung Warehouse',
            ],
            [
                'part_name' => 'Hydraulic Jack',
                'part_slug' => Str::slug('Hydraulic Jack'),
                'part_description' => 'Heavy-duty hydraulic jack for lifting massive loads.',
                'part_price' => 6200000,
                'part_category' => 'Lifting Equipment',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Surabaya Warehouse',
            ],
            [
                'part_name' => 'Safety Harness',
                'part_slug' => Str::slug('Safety Harness'),
                'part_description' => 'Full-body safety harness with multiple attachment points.',
                'part_price' => 1500000,
                'part_category' => 'Safety Equipment',
                'part_contact' => 'parts@constructionparts.com',
                'part_location' => 'Medan Warehouse',
            ],
            [
                'part_name' => 'Power Generator',
                'part_slug' => Str::slug('Power Generator'),
                'part_description' => 'Portable diesel power generator for construction sites.',
                'part_price' => 35000000,
                'part_category' => 'Electrical Equipment',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Jakarta Warehouse',
            ],
            [
                'part_name' => 'Drill Bit Set',
                'part_slug' => Str::slug('Drill Bit Set'),
                'part_description' => 'Industrial-grade drill bit set for heavy-duty drilling.',
                'part_price' => 2200000,
                'part_category' => 'Tools',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Yogyakarta Warehouse',
            ],
            [
                'part_name' => 'Laser Level',
                'part_slug' => Str::slug('Laser Level'),
                'part_description' => 'Professional-grade laser level with high precision.',
                'part_price' => 7500000,
                'part_category' => 'Measurement Tools',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Bandung Warehouse',
            ],
            [
                'part_name' => 'Crane Hook',
                'part_slug' => Str::slug('Crane Hook'),
                'part_description' => 'Heavy-duty crane hook for lifting and moving materials.',
                'part_price' => 4800000,
                'part_category' => 'Lifting Equipment',
                'part_contact' => 'parts@constructionparts.com',
                'part_location' => 'Surabaya Warehouse',
            ],
            [
                'part_name' => 'Excavator Rubber Track',
                'part_slug' => Str::slug('Excavator Rubber Track'),
                'part_description' => 'Durable rubber track for compact excavators.',
                'part_price' => 15000000,
                'part_category' => 'Undercarriage',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Medan Warehouse',
            ],
            [
                'part_name' => 'Air Impact Wrench',
                'part_slug' => Str::slug('Air Impact Wrench'),
                'part_description' => 'Powerful pneumatic impact wrench for heavy machinery.',
                'part_price' => 5500000,
                'part_category' => 'Tools',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Jakarta Warehouse',
            ],
            [
                'part_name' => 'Safety Goggles',
                'part_slug' => Str::slug('Safety Goggles'),
                'part_description' => 'Anti-fog safety goggles with UV protection.',
                'part_price' => 350000,
                'part_category' => 'Safety Equipment',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Yogyakarta Warehouse',
            ],
            [
                'part_name' => 'Pipe Fitting',
                'part_slug' => Str::slug('Pipe Fitting'),
                'part_description' => 'Industrial-grade hydraulic pipe fitting.',
                'part_price' => 750000,
                'part_category' => 'Hydraulic System',
                'part_contact' => 'parts@constructionparts.com',
                'part_location' => 'Bandung Warehouse',
            ],
            [
                'part_name' => 'Compactor Plate',
                'part_slug' => Str::slug('Compactor Plate'),
                'part_description' => 'Heavy-duty vibrating plate compactor for ground preparation.',
                'part_price' => 22000000,
                'part_category' => 'Compaction Equipment',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Surabaya Warehouse',
            ],
            [
                'part_name' => 'Wheel Bearing',
                'part_slug' => Str::slug('Wheel Bearing'),
                'part_description' => 'High-precision wheel bearing for heavy machinery.',
                'part_price' => 3200000,
                'part_category' => 'Undercarriage',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Medan Warehouse',
            ],
            [
                'part_name' => 'Portable Air Tank',
                'part_slug' => Str::slug('Portable Air Tank'),
                'part_description' => 'Compact compressed air storage tank for construction tools.',
                'part_price' => 2800000,
                'part_category' => 'Pneumatic Equipment',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Jakarta Warehouse',
            ],
            [
                'part_name' => 'Cutting Torch',
                'part_slug' => Str::slug('Cutting Torch'),
                'part_description' => 'Professional oxy-acetylene cutting torch for metal work.',
                'part_price' => 4500000,
                'part_category' => 'Welding Equipment',
                'part_contact' => 'parts@constructionparts.com',
                'part_location' => 'Yogyakarta Warehouse',
            ],
            [
                'part_name' => 'Pressure Washer',
                'part_slug' => Str::slug('Pressure Washer'),
                'part_description' => 'High-powered industrial pressure washer for equipment cleaning.',
                'part_price' => 12000000,
                'part_category' => 'Cleaning Equipment',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Bandung Warehouse',
            ],
            [
                'part_name' => 'Engine Coolant',
                'part_slug' => Str::slug('Engine Coolant'),
                'part_description' => 'High-performance engine coolant for heavy machinery.',
                'part_price' => 850000,
                'part_category' => 'Cooling System',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Surabaya Warehouse',
            ],
            [
                'part_name' => 'Hydraulic Oil',
                'part_slug' => Str::slug('Hydraulic Oil'),
                'part_description' => 'Premium grade hydraulic system oil.',
                'part_price' => 1200000,
                'part_category' => 'Hydraulic System',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Medan Warehouse',
            ],
            [
                'part_name' => 'Respirator Mask',
                'part_slug' => Str::slug('Respirator Mask'),
                'part_description' => 'Advanced respiratory protection for construction workers.',
                'part_price' => 750000,
                'part_category' => 'Safety Equipment',
                'part_contact' => 'parts@constructionparts.com',
                'part_location' => 'Jakarta Warehouse',
            ],
            [
                'part_name' => 'Hydraulic Breaker',
                'part_slug' => Str::slug('Hydraulic Breaker'),
                'part_description' => 'Heavy-duty hydraulic rock breaker attachment.',
                'part_price' => 45000000,
                'part_category' => 'Attachment',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Yogyakarta Warehouse',
            ],
            [
                'part_name' => 'Torque Wrench',
                'part_slug' => Str::slug('Torque Wrench'),
                'part_description' => 'Precision calibrated torque wrench for precise tightening.',
                'part_price' => 3500000,
                'part_category' => 'Tools',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Bandung Warehouse',
            ],
            [
                'part_name' => 'Pneumatic Drill',
                'part_slug' => Str::slug('Pneumatic Drill'),
                'part_description' => 'Industrial-grade compressed air powered drill.',
                'part_price' => 6200000,
                'part_category' => 'Tools',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Surabaya Warehouse',
            ],
            [
                'part_name' => 'Safety Gloves',
                'part_slug' => Str::slug('Safety Gloves'),
                'part_description' => 'Cut-resistant heavy-duty work gloves.',
                'part_price' => 250000,
                'part_category' => 'Safety Equipment',
                'part_contact' => 'parts@constructionparts.com',
                'part_location' => 'Medan Warehouse',
            ],
            [
                'part_name' => 'Electrical Junction Box',
                'part_slug' => Str::slug('Electrical Junction Box'),
                'part_description' => 'Weatherproof electrical connection box for outdoor use.',
                'part_price' => 1800000,
                'part_category' => 'Electrical Equipment',
                'part_contact' => 'support@constructionparts.com',
                'part_location' => 'Jakarta Warehouse',
            ],
            [
                'part_name' => 'Hydraulic Quick Coupler',
                'part_slug' => Str::slug('Hydraulic Quick Coupler'),
                'part_description' => 'Fast connect/disconnect hydraulic attachment system.',
                'part_price' => 7500000,
                'part_category' => 'Hydraulic System',
                'part_contact' => 'sales@constructionparts.com',
                'part_location' => 'Yogyakarta Warehouse',
            ],
            [
                'part_name' => 'Portable Generator',
                'part_slug' => Str::slug('Portable Generator'),
                'part_description' => 'Compact and powerful portable electricity generator.',
                'part_price' => 18000000,
                'part_category' => 'Electrical Equipment',
                'part_contact' => 'info@constructionparts.com',
                'part_location' => 'Bandung Warehouse',
            ]
        ];

        foreach ($parts as $part) {
            Part::create($part);
        }
    }
}