<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'product_slug' => 'heavy-duty-generator',
                'product_name' => 'Heavy-Duty Construction Generator',
                'product_description' => 'Powerful portable generator designed for rugged construction site environments. Provides reliable backup power for tools and equipment.',
                'product_image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXuLeh5bR4l3TIzWk4el8-WCar16DrZgM2Xw&s',
                'product_model_number' => 'CG-5500-HD',
                'product_power_output' => 5.5,
                'product_dimensions' => '2.4m x 1.8m x 2.2m',
                'product_fuel_type' => 'Diesel',
                'product_usage_instructions' => 'Ensure proper ventilation. Connect tools directly to generator outlets. Perform regular maintenance every 50 hours of use.',
                'product_price' => 45000000, 
            ],
            [
                'product_slug' => 'industrial-compressor',
                'product_name' => 'Portable Industrial Air Compressor',
                'product_description' => 'High-performance air compressor suitable for construction, painting, and pneumatic tool operations. Robust design for jobsite durability.',
                'product_image_url' => 'https://www.chamco.com/wp-content/uploads/2022/05/Sullair-825-Portable-Air-Compressor-1.jpg',
                'product_model_number' => 'AC-250-PRO',
                'product_power_output' => 3.5,
                'product_dimensions' => '3.6m x 2.4m x 3.0m',
                'product_fuel_type' => 'Electric',
                'product_usage_instructions' => 'Check oil levels before each use. Drain moisture trap weekly. Do not exceed maximum pressure rating.',
                'product_price' => 35000000, 
            ],
            [
                'product_slug' => 'concrete-mixer',
                'product_name' => 'Portable Concrete Mixer',
                'product_description' => 'Compact and efficient concrete mixer for small to medium construction projects. Easy to transport and simple to operate.',
                'product_image_url' => 'https://s.alicdn.com/@sc04/kf/H1f5409bf996f49e3925dd134aa82479cS.jpg_720x720q50.jpg',
                'product_model_number' => 'CM-350-COMPACT',
                'product_power_output' => 1.5,
                'product_dimensions' => '4.8m x 3.0m x 4.0m',
                'product_fuel_type' => 'Gasoline',
                'product_usage_instructions' => 'Clean mixer thoroughly after each use. Lubricate moving parts monthly. Wear protective gear during operation.',
                'product_price' => 25000000, 
            ],
            [
                'product_slug' => 'excavator-attachments',
                'product_name' => 'Universal Excavator Attachment Set',
                'product_description' => 'Versatile attachment kit for excavators, including multiple bucket sizes and specialized tools for various excavation tasks.',
                'product_image_url' => 'https://ahmcorp.com/cdn/shop/files/4_a7fb27bb-b933-4061-be78-9316f6cd0dbc.jpg?v=1729740481&width=1946',
                'product_model_number' => 'EXA-MULTI-TOOL',
                'product_power_output' => null,
                'product_dimensions' => 'Various sizes',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Inspect attachments for wear before each use. Ensure proper mounting and secure connections.',
                'product_price' => 75000000, 
            ],
            [
                'product_slug' => 'safety-scaffolding',
                'product_name' => 'Modular Construction Scaffolding',
                'product_description' => 'Adjustable and sturdy scaffolding system for safe working at height. Meets OSHA safety standards and provides reliable support.',
                'product_image_url' => 'https://cdn.peri.cloud/.imaging/l/dam/566a3ed8-3a60-4027-92a8-9b47e6659a16/41397/peri-up-modular-working-scaffold.jpg',
                'product_model_number' => 'SCF-500-MOD',
                'product_power_output' => null,
                'product_dimensions' => '1.0m x 6m x 2.0m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Always use fall protection. Inspect all connections before use. Do not exceed maximum weight capacity.',
                'product_price' => 60000000, 
            ], 
            [
                'product_slug' => 'laser-level',
                'product_name' => 'Self-Leveling Laser Level',
                'product_description' => 'Precision laser level for accurate leveling and alignment on construction sites.',
                'product_model_number' => 'LL-500',
                'product_power_output' => null,
                'product_dimensions' => '0.20m x 0.10m x 0.15m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Set on a stable surface. Ensure the laser is visible for accurate readings.',
                'product_price' => 15000000,
            ],
            [
                'product_slug' => 'demolition-hammer',
                'product_name' => 'Electric Demolition Hammer',
                'product_description' => 'Powerful electric demolition hammer for breaking concrete and masonry. Ideal for heavy-duty demolition tasks.',
                'product_model_number' => 'DH-1000',
                'product_power_output' => 1.2,
                'product_dimensions' => '0.60m x 0.25m x 0.15m',
                'product_fuel_type' => 'Electric',
                'product_usage_instructions' => 'Use appropriate safety gear. Ensure the tool is properly grounded before use.',
                'product_price' => 30000000,
            ],
            [
                'product_slug' => 'tile-cutter',
                'product_name' => 'Manual Tile Cutter',
                'product_description' => 'Efficient manual tile cutter for precise cuts on ceramic and porcelain tiles.',
                'product_model_number' => 'TC-200',
                'product_power_output' => null,
                'product_dimensions' => '0.80m x 0.30m x 0.20m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Score the tile surface before applying pressure to snap.',
                'product_price' => 12000000,
            ],
            [
                'product_slug' => 'power-drill',
                'product_name' => 'Cordless Power Drill',
                'product_description' => 'Versatile cordless drill for drilling and driving screws in various materials.',
                'product_model_number' => 'PD-300',
                'product_power_output' => 0.5,
                'product_dimensions' => '0.25m x 0.20m x 0.10m',
                'product_fuel_type' => 'Battery',
                'product_usage_instructions' => 'Charge battery fully before use. Use appropriate drill bits for different materials.',
                'product_price' => 20000000,
            ],
            [
                'product_slug' => 'safety-helmet',
                'product_name' => 'Construction Safety Helmet',
                'product_description' => 'Durable safety helmet designed to protect against head injuries on construction sites.',
                'product_model_number' => 'SH-100',
                'product_power_output' => null,
                'product_dimensions' => '0.25m x 0.25m x 0.15m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Wear at all times on site. Inspect for damage before use.',
                'product_price' => 5000000,
            ],
            [
                'product_slug' => 'safety-glasses',
                'product_name' => 'Protective Safety Glasses',
                'product_description' => 'Impact-resistant safety glasses for eye protection during construction work.',
                'product_model_number' => 'SG-200',
                'product_power_output' => null,
                'product_dimensions' => '0.15m x 0.05m x 0.05m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Wear at all times when working with power tools or hazardous materials.',
                'product_price' => 3000000,
            ],
            [
                'product_slug' => 'work-gloves',
                'product_name' => 'Heavy-Duty Work Gloves',
                'product_description' => 'Durable gloves designed for protection and grip during construction tasks.',
                'product_model_number' => 'WG-150',
                'product_power_output' => null,
                'product_dimensions' => '0.30m x 0.15m x 0.05m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Ensure a snug fit. Replace if damaged.',
                'product_price' => 1000000,
            ],
            [
                'product_slug' => 'measuring-tape',
                'product_name' => '25m Measuring Tape',
                'product_description' => 'Durable measuring tape for accurate measurements on construction sites.',
                'product_model_number' => 'MT-25',
                'product_power_output' => null,
                'product_dimensions' => '0.10m x 0.10m x 0.05m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Lock tape in place for accurate measurements.',
                'product_price' => 500000,
            ],
            [
                'product_slug' => 'screwdriver-set',
                'product_name' => 'Precision Screwdriver Set',
                'product_description' => 'Comprehensive set of screwdrivers for various applications in construction and repair.',
                'product_model_number' => 'SS-10',
                'product_power_output' => null,
                'product_dimensions' => '0.30m x 0.10m x 0.05m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Select the appropriate screwdriver for the screw type. Store in a dry place.',
                'product_price' => 800000,
            ],
            [
                'product_slug' => 'saw',
                'product_name' => 'Hand Saw',
                'product_description' => 'Manual hand saw for cutting wood and other materials.',
                'product_model_number' => 'HS-100',
                'product_power_output' => null,
                'product_dimensions' => '0.70m x 0.10m x 0.05m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Use steady strokes for efficient cutting. Keep blade sharp.',
                'product_price' => 1500000,
            ],
            [
                'product_slug' => 'level',
                'product_name' => 'Spirit Level',
                'product_description' => 'Essential tool for ensuring surfaces are level and plumb.',
                'product_model_number' => 'SL-200',
                'product_power_output' => null,
                'product_dimensions' => '0.60m x 0.05m x 0.05m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Place on the surface to check level. Adjust as necessary.',
                'product_price' => 2000000,
            ],
            [
                'product_slug' => 'safety-harness',
                'product_name' => 'Construction Safety Harness',
                'product_description' => 'Adjustable safety harness for fall protection on construction sites.',
                'product_model_number' => 'SH-200',
                'product_power_output' => null,
                'product_dimensions' => '0.50m x 0.30m x 0.10m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Ensure proper fit before use. Inspect for wear regularly.',
                'product_price' => 4000000,
            ],
            [
                'product_slug' => 'tool-belt',
                'product_name' => 'Heavy-Duty Tool Belt',
                'product_description' => 'Durable tool belt with multiple pockets for easy access to tools.',
                'product_model_number' => 'TB-300',
                'product_power_output' => null,
                'product_dimensions' => '1.00m x 0.15m x 0.05m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Wear securely around the waist. Organize tools for easy access.',
                'product_price' => 2500000,
            ],
            [
                'product_slug' => 'work-boots',
                'product_name' => 'Steel-Toe Work Boots',
                'product_description' => 'Protective work boots with steel toe for safety on construction sites.',
                'product_model_number' => 'WB-100',
                'product_power_output' => null,
                'product_dimensions' => '0.30m x 0.30m x 0.15m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Ensure proper fit. Replace if worn out.',
                'product_price' => 3000000,
            ],
            [
                'product_slug' => 'concrete-saw',
                'product_name' => 'Gas-Powered Concrete Saw',
                'product_description' => 'Powerful saw for cutting concrete and masonry materials.',
                'product_model_number' => 'CS-500',
                'product_power_output' => 5.0,
                'product_dimensions' => '1.00m x 0.50m x 0.40m',
                'product_fuel_type' => 'Gasoline',
                'product_usage_instructions' => 'Wear protective gear. Follow safety guidelines for operation.',
                'product_price' => 70000000,
            ],
            [
                'product_slug' => 'grinder',
                'product_name' => 'Angle Grinder',
                'product_description' => 'Versatile angle grinder for cutting, grinding, and polishing.',
                'product_model_number' => 'AG-300',
                'product_power_output' => 2.0,
                'product_dimensions' => '0.40m x 0.15m x 0.10m',
                'product_fuel_type' => 'Electric',
                'product_usage_instructions' => 'Use appropriate discs for different tasks. Always wear safety goggles.',
                'product_price' => 25000000,
            ],
            [
                'product_slug' => 'jackhammer',
                'product_name' => 'Electric Jackhammer',
                'product_description' => 'Powerful electric jackhammer for breaking up concrete and asphalt.',
                'product_model_number' => 'JH-1000',
                'product_power_output' => 1.5,
                'product_dimensions' => '0.80m x 0.30m x 0.20m',
                'product_fuel_type' => 'Electric',
                'product_usage_instructions' => 'Use appropriate chisels for different tasks. Always wear safety goggles and gloves.',
                'product_price' => 40000000,
            ],
            [
                'product_slug' => 'sandblaster',
                'product_name' => 'Portable Sandblaster',
                'product_description' => 'Compact sandblaster for cleaning and preparing surfaces.',
                'product_model_number' => 'SB-200',
                'product_power_output' => null,
                'product_dimensions' => '0.50m x 0.30m x 0.20m',
                'product_fuel_type' => null,
                'product_usage_instructions' => 'Use appropriate abrasive media for different tasks. Wear protective gear.',
                'product_price' => 15000000,
            ],
            [
                'product_slug' => 'welding-machine',
                'product_name' => 'MIG Welding Machine',
                'product_description' => 'Versatile MIG welding machine for welding steel and aluminum.',
                'product_model_number' => 'WM-300',
                'product_power_output' => 3.0,
                'product_dimensions' => '0.60m x 0.30m x 0.20m',
                'product_fuel_type' => 'Electric',
                'product_usage_instructions' => 'Use appropriate welding wire for different tasks. Always wear safety goggles and gloves.',
                'product_price' => 50000000,
            ],
            [
                'product_slug' => 'drill-press',
                'product_name' => 'Bench Drill Press',
                'product_description' => 'Precise bench drill press for drilling accurate holes.',
                'product_model_number' => 'DP-200',
                'product_power_output' => 1.0,
                'product_dimensions' => '0.80m x 0.40m x 0.30m',
                'product_fuel_type' => 'Electric',
                'product_usage_instructions' => 'Use appropriate drill bits for different materials. Always wear safety goggles.',
                'product_price' => 30000000,
            ],
            [
                'product_slug' => 'impact-wrench',
                'product_name' => 'Cordless Impact Wrench',
                'product_description' => 'Powerful cordless impact wrench for loosening bolts and nuts.',
                'product_model_number' => 'IW-300',
                'product_power_output' => 2.5,
                'product_dimensions' => '0.30m x 0.20m x 0.10m',
                'product_fuel_type' => 'Battery',
                'product_usage_instructions' => 'Use appropriate sockets for different tasks. Always wear safety goggles.',
                'product_price' => 25000000,
            ],
            [
                'product_slug' => 'circular-saw',
                'product_name' => 'Cordless Circular Saw',
                'product_description' => 'Versatile cordless circular saw for cutting wood and metal.',
                'product_model_number' => 'CS-200',
                'product_power_output' => 1.5,
                'product_dimensions' => '0.40m x 0.20m x 0.10m',
                'product_fuel_type' => 'Battery',
                'product_usage_instructions' => 'Use appropriate blades for different materials. Always wear safety goggles.',
                'product_price' => 20000000,
            ],
            [
                'product_slug' => 'reciprocating-saw',
                'product_name' => 'Cordless Reciprocating Saw',
                'product_description' => 'Powerful cordless reciprocating saw for demolition and pruning.',
                'product_model_number' => 'RS-300',
                'product_power_output' => 2.0,
                'product_dimensions' => '0.50m x 0.20m x 0.10m',
                'product_fuel_type' => 'Battery',
                'product_usage_instructions' => 'Use appropriate blades for different tasks. Always wear safety goggles.',
                'product_price' => 30000000,
            ],
        ];
        foreach ($products as $product) {
            Product::create($product);
        }
    }
}